services:
  api-tests-dev:
    build: .
    image: oskarsstalgis/api-tests:latest
    container_name: api-tests-dev
    volumes:
      -$PWD/test-reports/dev:/api-test-automation/mochawesome-report/
    command: run greetings greetings_dev
    networks:
      - greetings-app-network-compose
  api-tests-stg:
    build: .
    image: oskarsstalgis/api-tests:latest
    container_name: api-tests-stg
    volumes:
      -$PWD/test-reports/stg:/api-test-automation/mochawesome-report/
    command: run greetings greetings_stg
    networks:
      - greetings-app-network-compose
  api-tests-prod:
    build: .
    image: oskarsstalgis/api-tests:latest
    container_name: api-tests-prod
    volumes:
      -$PWD/test-reports/prd:/api-test-automation/mochawesome-report/
    command: run greetings greetings_prod
    networks:
      - greetings-app-network-compose

networks:
  greetings-app-network-compose:
    external: true

